### ISSUE TITLE
I get error 

### ISSUE THREAD

**Issue by Muhammed1244** [HimanchalChandra/Object-Detection-with-Voice-Feedback-YOLO-v3-and-gTTS#1]
I get this error:

```
usage: script.py [-h] -i IMAGE -y YOLO [-c CONFIDENCE] [-t THRESHOLD]
script.py: error: the following arguments are required: -i/--image, -y/--yolo
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2
```
How can I solve?

**Comment by HimanchalChandra** [comment]
It is asking for input image path and Yolo weights path. You need to download the weights first (check note in readme file).

For example if I had input image in images folder and yolo weights in yolov3 folder then the run script would be:
python script.py --image images --yolo yolov3

**Comment by MrAdithya21** [comment]
I got this error:

(H, W) = input_image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by HimanchalChandra** [comment]
@MrAdithya21 make sure you are passing image correctly
