### ISSUE TITLE
How to run , pass prameters 

### ISSUE THREAD

**Issue by harishkondepati** [HimanchalChandra/Object-Detection-with-Voice-Feedback-YOLO-v3-and-gTTS#2]
ap = argparse.ArgumentParser()
ap.add_argument("-i", "--image", required=True,
	help="path to input image")
ap.add_argument("-y", "--yolo", required=True,
	help="base path to YOLO directory")
ap.add_argument("-c", "--confidence", type=float, default=0.5,
	help="minimum probability to filter weak detections")
ap.add_argument("-t", "--threshold", type=float, default=0.3,
	help="threshold when applyong non-maxima suppression")
args = vars(ap.parse_args())

**Comment by HimanchalChandra** [comment]
It is asking for input image path and Yolo weights path. You need to download the weights first (check note in readme file).

For example, if I had input image in the images folder and Yolo weights in the yolov3 folder then the run script would be:
python script.py --image images --yolo yolov3

**Comment by harishkondepati** [comment]
Im Getting Error While running your script.py

ERROR : PS D:\PythonProjrects\yolo> python script.py --image images --yolo
yolov3
Traceback (most recent call last):
FileNotFoundError: [Errno 2] No such file or directory:
'yolov3\\yolo/coco.names'
  File "D:\PythonProjrects\yolo\script.py", line 22, in <module>
    LABELS = open(labelsPath).read().strip().split("\n")
FileNotFoundError: [Errno 2] No such file or directory: 'yolov3\\coco.names'

please help me to run this script ,it's a humble request
find the below attachment..please

**Comment by HimanchalChandra** [comment]
Do you have coco.names file in yolov3 folder?

**Comment by harishkondepati** [comment]
In my screenshot you can see my project structure..
All the files are in root folder..

According to that can you suggest plz..

**Comment by HimanchalChandra** [comment]
Create 2 folders inside yolo, images, and yolov3. Keep the weights in yolov3 and test image in images, then run the script.
